task/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='list'),
    path('update_task/<str:pk>/', views.updateTask, name='update_task'),
    path('delete_task/<str:pk>/', views.deleteTask, name='delete_task'),

]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('task.urls', 'task'), namespace='task')),
    path('admin/', admin.site.urls),
]

task/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=200)
    complete = models.BooleanField(default=False)
    creation_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

task/forms.py
from django import forms
from .models import *


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = '__all__'

task/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import Task


def index(request):
    tasks = Task.objects.all()

    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect('/')
    context = {'tasks': tasks, 'form': form}
    return render(request, 'task/list.html', context)


def updateTask(request, pk):
    task = Task.objects.get(id=pk)

    form = TaskForm(instance=task)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
        return redirect('/')
    context = {'form': form}
    return render(request, 'task/update_task.html', context)


def deleteTask(request, pk):
    item = Task.objects.get(id=pk)

    if request.method == 'POST':
        item.delete()
        return redirect('/')

    context = {'item': item}
    return render(request, 'task/delete.html', context)

task/templates/task/delete.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<style>

    body{
		background-color: #09b300;
	}
	.center-column{
		width:600px;
		margin: 20px auto;
		padding:20px;
		background-color: #fff;
		border-radius: 3px;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
	}
	.item-row{
		background-color: #53a379;
		margin: 10px;
		padding: 20px;
		border-radius: 3px;
		color: #fff;
		font-size: 16px;
		box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
	}
	.btn-danger{
		background-color: #ffae19;
		border-color: #e59400;
	}

</style>
<body>
    <div class="center-column">
        <h1 style="color: #ff3d3d;">Are you sure you are going to delete this item?</h1>
        <div class="item-row">
            <p>{{ item }}</p>
        </div>

        <form method="post" action="">
            {% csrf_token %}
            <input type="submit" value="Confirmar" name="Delete Task" class="btn btn-sm btn-danger">
            <a href="{% url 'task:list' %}" class="btn btn-info">Cancel</a>
        </form>
    </div>
</body>

task/templates/task/list.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<style>

	body{
		background-color: #09b300;
	}

	input{
		width: 100%;
		padding: 12px 20px;
		margin: 8px 0;
		box-sizing: border-box;
	}

	input::placeholder {
	  color: #d3d3d3;
	}

	.submit{
		background-color: #0052b8;
	}

	.center-column{
		width:600px;
		margin: 20px auto;
		padding:20px;
		background-color: #fff;
		border-radius: 3px;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
	}

	.item-row{
		background-color: #53a379;
		margin: 10px;
		padding: 20px;
		border-radius: 3px;
		color: #fff;
		font-size: 16px;
		box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
	}

	.btn-danger{
		background-color: #ffae19;
		border-color: #e59400;
	}

</style>

<div class="center-column">

	<form method="POST" action="/">
		{% csrf_token %}
		{{ form.title }}
		<input class="btn btn-info" type="submit" value="Submit" name="Create Task">
	</form>

	<div class="todo-list">

	{% for task in tasks %}
		<div class="item-row">
			<a class="btn btn-sm btn-info" href="{% url 'task:update_task' task.id %}">update</a>
			<a class="btn btn-sm btn-danger" href="{% url 'task:delete_task' task.id %}">delete</a>

			{% if task.complete == True %}
			<strike>{{ task }}</strike>
			{% else %}
			<span>{{ task }}</span>
			{% endif %}
		</div>
	{% endfor %}
	</div>
</div>

task/templates/task/update_task.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<style>

	body{
		background-color: #09b300;
	}

	input{
		width: 100%;
		padding: 12px 20px;
		margin: 8px 0;
		box-sizing: border-box;
	}

	input::placeholder {
	  color: #d3d3d3;
	}

	.submit{
		background-color: #0052b8;
	}

	.center-column{
		width:600px;
		margin: 20px auto;
		padding:20px;
		background-color: #fff;
		border-radius: 3px;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
	}

	.item-row{
		background-color: #53a379;
		margin: 10px;
		padding: 20px;
		border-radius: 3px;
		color: #fff;
		font-size: 16px;
		box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
	}


</style>
<body>
    <div class="center-column">
        <form method="post" action="">
            {% csrf_token %}
            {{ form.title }}
            <p class="item-row">COMPLETED: {{ form.complete }}</p>
            <input type="submit" value="Concluído" name="Update Task" class="btn btn-info">
        </form>
    </div>
</body>